### ISSUE TITLE
Enhance Failed Match Alert

### ISSUE THREAD

**Issue by MicahZoltu** [Zoltu/bags-client#33]
In user testing, users seem to not notice when they have failed search terms.  We need to figure out a way to bring more attention to the failure so the user notices.  Perhaps some kind of warning/error bar (red/yellow) or warning/alert icon?

**Comment by arpitux** [comment]
I can't color the failure panel's background because we show tags in it which are already colorful. Though I have tried to highlight the panel with darker+bigger box shadow. Darker font color and a orange color alert icon.

**Comment by MicahZoltu** [comment]
Can we color the header bar in some way (the bit that says "We couldn't find an exact match ...")?

Alternatively, could we put a red or orange colored border around the whole thing, to help draw attention to it?

**Comment by arpitux** [comment]
Can we close this issue?
